name: "sample reacts CI pipelinw / workflows"

on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: "Setup Node Js"
        uses: actions/setip=node@v4
        with:
          node-version: '16'
